### ISSUE TITLE
Custom menu not compatible with Bootstrap themes

### ISSUE THREAD

**Issue by plegall** [Piwigo/AMenuManager#3]
![bug-amm-bootstrap](https://user-images.githubusercontent.com/9326959/27908620-160ecd34-624d-11e7-803c-f521b5556277.png)

**Comment by Romtom03** [comment]
I guess my problem stems from the same source.
After updating the template Bootstrap Darkroom to 1.5.18 I received the following Error while trying to access the gallery

`Fatal error: Uncaught --> Smarty: Missing template name <-- thrown in /piwigo/include/smarty/libs/sysplugins/smarty_template_source.php on line 157`

I tracked it down, to be some problem when the plugin Advanced Menu Manager 3.2.12 is running.

Don't know whether the template or the plugin needs some fixing. Hope you know better. ;-)
